version: '3.9'

services:
  mysql:
    image: mysql:8.0.33
    container_name: backend-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: Password123
    restart: always
    networks:
      - mysql-network
    command: --default-authentication-plugin=mysql_native_password

  cli:
    image: mysql:8.0.33
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword library

networks:
  mysql-network:
    driver: bridge



